# rails _5.2.4.3_ new .qa_server_app --database=mysql
# rm .qa_server_app/config/database.yml # use ENV for database configuration
# docker-compose build
# docker-compose up app
version: '3.5'
services:
  app: &app
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT: test
#        EXTRA_APK_PACKAGES: 'git postgresql-dev'
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=mysql://qa_server_user:ld4p@mysql/qa_server?pool=5
      - REDIS_HOST=redis
    depends_on:
      - db_migrate
      - memcached
      - mysql
      - redis
      - imagemagick
    ports:
      - 3000:3000
    volumes:
      - .qa_server_app:/data

  db_migrate:
    <<: *app
    environment:
      - DATABASE_URL=mysql://qa_server_user:ld4p@mysql/qa_server?pool=5
      - REDIS_HOST=redis
    command:
      - bundle
      - exec
      - rails
      - db:create
      - db:migrate
    depends_on:
      - mysql
    ports: []
    volumes:
      - .qa_server_app:/data

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=qa_server_user
      - MYSQL_PASSWORD=ld4p
      - MYSQL_DB=qa_server
      - MYSQL_HOST_AUTH_METHOD=trust
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql/data

  mysql_admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    image: bitnami/memcached
    ports:
      - '11211:11211'

  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data

  imagemagick:
    image: dpokidov/imagemagick

volumes:
  db:
  redis:
