AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Description goes here
Parameters:
  TaskDefinitionName:
    Type: String
Resources:
# TODO: Add a cluster definition 
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name:
            Ref: TaskDefinitionName
          Cpu: 0
          EnvironmentFiles: 
            - Type: s3
              Value: arn:aws:s3:::ld4l-qa-server/qa-server-container-with-db.env
          Essential: True
          Image: 092831676293.dkr.ecr.us-east-1.amazonaws.com/qa-server/qa-server-app:latest
          Links: 
            - qa-mariadb: qa-mariadb
          LogConfiguration: 
            - LogDriver: awslogs
              Options:
              - awslogs-group: /ecs/qa-server-app
              - awslogs-region: us-east-1
              - awslogs-stream-prefix: ecs
          MemoryReservation: 512
          MountPoints: 
            - SourceVolume: qa-server-authorities
              ContainerPath: /app/ld4p/qa_server-webapp/config/authorities
          PortMappings: 
            HostPort: 3000
            Protocol: tcp
            ContainerPort: 3000
        - Name: qa-mariadb-cf
          Cpu: 0
          EnvironmentFiles: 
            - Type: s3
              Value: arn:aws:s3:::ld4l-qa-server/qa-server-container-with-db.env
          Essential: True
          Image: mariadb:latest
          LogConfiguration: 
            - LogDriver: awslogs
              Options:
              - awslogs-group: /ecs/qa-mariadb-cf
              - awslogs-region: us-east-1
              - awslogs-stream-prefix: ecs
          MemoryReservation: 512
          MountPoints: 
            - SourceVolume: db-mysql-data
              ContainerPath: /var/lib/mysql/data
          PortMappings: 
            HostPort: 3306
            Protocol: tcp
            ContainerPort: 3306

      Cpu: 1024
      ExecutionRoleArn: arn:aws:iam::092831676293:role/ecsTaskExecutionRole
      Family: qa-server-with-db-cf
      Memory: 1024
      NetworkMode: bridge
      RequiresCompatibilities: 
        - EC2
      Tags: 
        - Tag
      TaskRoleArn: arn:aws:iam::092831676293:role/ecsTaskExecutionRole
      Volumes: 
        - Name: db-mysql-data
          FilesystemId: fs-402461c2
          EFSVolumeConfiguration:
            AuthorizationConfig: 
            - Iam: DISABLED
              AccessPointId: fsap-0861798cebbd27cbe
          RootDirectory: "/"
          TransitEncryption: ENABLED
        - Name: qa-server-authorities
          FilesystemId: fs-402461c2
          EFSVolumeConfiguration:
            AuthorizationConfig: 
            - Iam: DISABLED
              AccessPointId: fsap-01817d5defea7264d
          RootDirectory: "/"
          TransitEncryption: ENABLED

