AWSTemplateFormatVersion: "2010-09-09"
Description: >
  1. Review the parameters below and ensure that they are appropriate to your environment. Then deploy with this aws cli command:
    aws cloudformation create-stack --stack-name qa-server-prerequisites \
    --template-body file://./aws-prerequisites.yaml \
    --parameters file://./prerequisites.env
  2. The outputs of this template file will be used by the aws-cloudformation.yaml template.
Parameters:
  AWSVpcId:
    Type: String
    Default: ''
    Description: Your AWS VPC ID. It should look like vpc-4d4bec2b. Required for load balancer configuration and security group rules.
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select two subnets in your selected VPC. The values must be separated by commas.
  S3BucketName:
    Type: String
    Default: ''
    Description: The name you wish your S3 bucket to have. This bucket name must be unique within the entire AWS region, so you will have to change the value provided here to one that is not already in use.
  EFSName:
    Type: String
    Description: The name you wish your EFS filesystem to have. This name must be unique within your account.
  EFSAuthoritiesAccessPoint:
    Type: String
    Default: ''
    Description: The name you wish your EFS authorities access point to have. This will create an access point where your service's authorities files will live. After it is created, you will need to connect to this access point to upload at least one authority file.
  EFSDatabaseAccessPoint:
    Type: String
    Default: ''
    Description: The name you wish your EFS database access point to have. This will create an access point that the database will use to store its datafiles.
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  Filesystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      FileSystemTags:
        - Key: "Name"
          Value: !Ref EFSName
  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref Filesystem
      SecurityGroups: 
        - !Ref NFSSecurityGroup
      SubnetId: !Select [ 0, !Ref SubnetIds ]
  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref Filesystem
      SecurityGroups: 
        - !Ref NFSSecurityGroup
      SubnetId: !Select [ 1, !Ref SubnetIds ]
  NFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Permit access over port 2049"
      GroupName: !Ref EFSName
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          Description: Wide open to the world
          FromPort: 2049
          IpProtocol: tcp
          ToPort: 2049
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          Description: Wide open to the world
          FromPort: 2049
          IpProtocol: tcp
          ToPort: 2049
      VpcId: !Ref AWSVpcId
  AuthorityAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties: 
      AccessPointTags: 
        - Key: "Name"
          Value: !Ref EFSAuthoritiesAccessPoint
      FileSystemId: !Ref Filesystem
      PosixUser:
        Gid: 0
        Uid: 0
      RootDirectory: 
        Path: "/authorities"
  DatabaseAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties: 
      AccessPointTags: 
        - Key: "Name"
          Value: !Ref EFSDatabaseAccessPoint
      FileSystemId: !Ref Filesystem
      PosixUser:
        Gid: 0
        Uid: 0
      RootDirectory: 
        Path: "/db-mysql-data"
  EfsLocation:
    Type: AWS::DataSync::LocationEFS
    Properties:
      EfsFilesystemArn: !Sub arn:${AWS::Partition}:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${Filesystem}
      Ec2Config:
        SecurityGroupArns:
          - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:security-group/${NFSSecurityGroup}
        SubnetArn: !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${EFSMountTarget2.SubnetId}
  S3Location:
    Type: AWS::DataSync::LocationS3
    Properties:
      S3BucketArn: !GetAtt Bucket.Arn
      S3Config:
        BucketAccessRoleArn: !GetAtt DataSyncRole.Arn
      S3StorageClass: STANDARD
  DataSyncRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [datasync.amazonaws.com]
          Action: ['sts:AssumeRole']
      Policies:
      - PolicyName: {"Fn::Join": ["", [{"Ref": "AWS::Region"}, "-qa-datasync-role-policy"]]}
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['s3:GetBucketLocation', 's3:ListBucket', 's3:ListBucketMultipartUploads']
            Resource: !Sub arn:${AWS::Partition}:s3:::${S3BucketName}
          - Effect: Allow
            Action: ['s3:AbortMultipartUpload', 's3:DeleteObject', 's3:GetObject', 's3:ListMultipartUploadParts', 's3:PutObjectTagging', 's3:GetObjectTagging', 's3:PutObject']
            Resource: !Sub arn:${AWS::Partition}:s3:::${S3BucketName}
  S3ToEfsTask:
    Type: AWS::DataSync::Task
    Properties:
      Name: 'Copy S3 to EFS'
      SourceLocationArn: !Ref S3Location
      DestinationLocationArn: !Ref EfsLocation
      Schedule:
        ScheduleExpression: cron(30 * * * ? *)
      Options:
        OverwriteMode: 'ALWAYS'
        PreserveDeletedFiles: 'REMOVE'
        TransferMode: 'CHANGED'

Outputs:
  S3BucketName:
    Value: !Ref Bucket
  VolumeId:
    Value: !Ref Filesystem
  AuthorityAccessPointId:
    Value: !Ref AuthorityAccessPoint
  DatabaseAccessPointId:
    Value: !Ref DatabaseAccessPoint
  S3ToEfsTask:
    Value: !Ref S3ToEfsTask
    