default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  socket: /var/lib/mysql/mysql.sock
  strict: false

development:
  <<: *default
  database: <%= "#{ENV['MYSQL_DATABASE_NAME_PREFIX']}_development" %>
  username: <%= "#{ENV['MYSQL_USER']}" %>
  password: <%= "#{ENV['MYSQL_PASSWORD']}" %>
  host:     <%= "#{ENV['MYSQL_HOST']}" %>
  pool:     <%= ENV["MYSQL_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

integration:
  <<: *default
  database: <%= "#{ENV['MYSQL_DATABASE_NAME_PREFIX']}_integration" %>
  username: <%= "#{ENV['MYSQL_USER']}" %>
  password: <%= "#{ENV['MYSQL_PASSWORD']}" %>
  host:     <%= "#{ENV['MYSQL_HOST']}" %>
  pool:     <%= ENV["MYSQL_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

staging:
  <<: *default
  database: <%= "#{ENV['MYSQL_DATABASE_NAME_PREFIX']}_staging" %>
  username: <%= "#{ENV['MYSQL_USER']}" %>
  password: <%= "#{ENV['MYSQL_PASSWORD']}" %>
  host:     <%= "#{ENV['MYSQL_HOST']}" %>
  pool:     <%= ENV["MYSQL_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

production:
  <<: *default
  database: <%= "#{ENV['MYSQL_DATABASE_NAME_PREFIX']}" %>
  username: <%= "#{ENV['MYSQL_USER']}" %>
  password: <%= "#{ENV['MYSQL_PASSWORD']}" %>
  host:     <%= "#{ENV['MYSQL_HOST']}" %>
  pool:     <%= ENV["MYSQL_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
