---
authority:
  service: ld4l_cache
  context: true
search:
  -
    query: 'mark twain'
  -
    query: 'mark twain'
    subauth: 'work'
  -
    query: 'mark twain'
    subauth: 'superwork'
  -
    query: 'mark twain'
    subauth: 'instance'
term:
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/97d309f7-ef59-397b-9500-40c4db12aefc'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/6229961'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Instance/COLORADOocm46976428'
