---
authority:
  service: ld4l_cache
  context: true
search:
  -
    query: 'mark twain'
  -
    query: 'mark twain'
    subauth: 'work'
  -
    query: 'mark twain'
    subauth: 'superwork'
  -
    query: 'mark twain'
    subauth: 'instance'
term:
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/171591'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/311de1d3-4900-33a9-a6d4-ae21813a4538'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Instance/CORNELL1975476'
