---
authority:
  service: ld4l_cache
  context: true
search:
  -
    query: 'schubert'
  -
    query: 'schubert'
    subauth: 'work'
  -
    query: 'schubert'
    subauth: 'superwork'
  -
    query: 'schubert'
    subauth: 'instance'
term:
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/17986921'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/777687'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Instance/UCDAVIS990036367860403126'
