---
authority:
  service: ld4l_cache
  context: true
search:
  -
    query: 'mark twain'
  -
    query: 'mark twain'
    subauth: 'work'
  -
    query: 'poem'
    subauth: 'superwork'
  -
    query: 'mark twain'
    subauth: 'instance'
term:
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/27312913'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/583119'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Instance/HARVARD004572228-5'
